In [3]:
import numpy as np
import pandas as pd
import os

In [5]:
os.chdir("/mnt/myParts/sda2/myPythonEnvs/Normal Modules/FIFA")

In [111]:
db = pd.read_csv("data.csv")

In [113]:
pd.set_option('display.max_columns', None)

In [114]:
db.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,Value,Wage,Special,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,Body Type,Real Face,Position,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,https://cdn.sofifa.org/teams/2/light/241.png,€110.5M,€565K,2202,Left,5.0,4.0,4.0,Medium/ Medium,Messi,Yes,RF,10.0,"Jul 1, 2004",NaN,2021,5'7,159lbs,88+2,88+2,88+2,92+2,93+2,93+2,93+2,92+2,93+2,93+2,93+2,91+2,84+2,84+2,84+2,91+2,64+2,61+2,61+2,61+2,64+2,59+2,47+2,47+2,47+2,59+2,84.0,95.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,96.0,91.0,86.0,91.0,95.0,95.0,85.0,68.0,72.0,59.0,94.0,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,https://cdn.sofifa.org/teams/2/light/45.png,€77M,€405K,2228,Right,5.0,4.0,5.0,High/ Low,C. Ronaldo,Yes,ST,7.0,"Jul 10, 2018",NaN,2022,6'2,183lbs,91+3,91+3,91+3,89+3,90+3,90+3,90+3,89+3,88+3,88+3,88+3,88+3,81+3,81+3,81+3,88+3,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3,84.0,94.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,94.0,89.0,91.0,87.0,96.0,70.0,95.0,95.0,88.0,79.0,93.0,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,https://cdn.sofifa.org/teams/2/light/73.png,€118.5M,€290K,2143,Right,5.0,5.0,5.0,High/ Medium,Neymar,Yes,LW,10.0,"Aug 3, 2017",NaN,2022,5'9,150lbs,84+3,84+3,84+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,89+3,88+3,81+3,81+3,81+3,88+3,65+3,60+3,60+3,60+3,65+3,60+3,47+3,47+3,47+3,60+3,79.0,87.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,95.0,94.0,90.0,96.0,94.0,84.0,80.0,61.0,81.0,49.0,82.0,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,https://cdn.sofifa.org/teams/2/light/11.png,€72M,€260K,1471,Right,4.0,3.0,1.0,Medium/ Medium,Lean,Yes,GK,1.0,"Jul 1, 2011",NaN,2020,6'4,168lbs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,13.0,21.0,50.0,13.0,18.0,21.0,19.0,51.0,42.0,57.0,58.0,60.0,90.0,43.0,31.0,67.0,43.0,64.0,12.0,38.0,30.0,12.0,68.0,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,https://cdn.sofifa.org/teams/2/light/10.png,€102M,€355K,2281,Right,4.0,5.0,4.0,High/ High,Normal,Yes,RCM,7.0,"Aug 30, 2015",NaN,2023,5'11,154lbs,82+3,82+3,82+3,87+3,87+3,87+3,87+3,87+3,88+3,88+3,88+3,88+3,87+3,87+3,87+3,88+3,77+3,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3,93.0,82.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,91.0,78.0,76.0,79.0,91.0,77.0,91.0,63.0,90.0,75.0,91.0,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [125]:
db1 = db[["Name", "Age", "Overall", "Position", "Wage", "Value", "Club", "Nationality"]]

In [126]:
db1.head()

,Name,Age,Overall,Position,Wage,Value,Club,Nationality
0,L. Messi,31,94,RF,€565K,€110.5M,FC Barcelona,Argentina
1,Cristiano Ronaldo,33,94,ST,€405K,€77M,Juventus,Portugal
2,Neymar Jr,26,92,LW,€290K,€118.5M,Paris Saint-Germain,Brazil
3,De Gea,27,91,GK,€260K,€72M,Manchester United,Spain
4,K. De Bruyne,27,91,RCM,€355K,€102M,Manchester City,Belgium

In [127]:
def price(abc):
    if abc[-1].isdigit():
        return float(abc[1:])
    else:
        res = float(abc[1:-1])
        if abc[-1] == 'K':
            return res*1000
        elif abc[-1]=='M':
            return res*1000000

In [128]:
db1["Wage"] = db1["Wage"].apply(price)
db1["Value"] = db1["Value"].apply(price)

<ipython-input-128-6552960f0e8a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  db1["Wage"] = db1["Wage"].apply(price)
<ipython-input-128-6552960f0e8a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  db1["Value"] = db1["Value"].apply(price)

In [129]:
db1.head()

,Name,Age,Overall,Position,Wage,Value,Club,Nationality
0,L. Messi,31,94,RF,565000.0,110500000.0,FC Barcelona,Argentina
1,Cristiano Ronaldo,33,94,ST,405000.0,77000000.0,Juventus,Portugal
2,Neymar Jr,26,92,LW,290000.0,118500000.0,Paris Saint-Germain,Brazil
3,De Gea,27,91,GK,260000.0,72000000.0,Manchester United,Spain
4,K. De Bruyne,27,91,RCM,355000.0,102000000.0,Manchester City,Belgium

In [130]:
db1.sort_values(["Wage", "Value"], ascending=False).head(30)

,Name,Age,Overall,Position,Wage,Value,Club,Nationality
0,L. Messi,31,94,RF,565000.0,110500000.0,FC Barcelona,Argentina
7,L. Suárez,31,91,RS,455000.0,80000000.0,FC Barcelona,Uruguay
6,L. Modrić,32,91,RCM,420000.0,67000000.0,Real Madrid,Croatia
1,Cristiano Ronaldo,33,94,ST,405000.0,77000000.0,Juventus,Portugal
8,Sergio Ramos,32,91,RCB,380000.0,51000000.0,Real Madrid,Spain
4,K. De Bruyne,27,91,RCM,355000.0,102000000.0,Manchester City,Belgium
11,T. Kroos,28,90,LCM,355000.0,76500000.0,Real Madrid,Germany
36,G. Bale,28,88,ST,355000.0,60000000.0,Real Madrid,Wales
5,E. Hazard,27,91,LF,340000.0,93000000.0,Chelsea,Belgium
32,Coutinho,26,88,LW,340000.0,69500000.0,FC Barcelona,Brazil
30,Isco,26,88,LW,315000.0,73500000.0,Real Madrid,Spain
28,J. Rodríguez,26,88,LAM,315000.0,69500000.0,FC Bayern München,Colombia
20,Sergio Busquets,29,89,CDM,315000.0,51500000.0,FC Barcelona,Spain
23,S. Agüero,30,89,ST,300000.0,64500000.0,Manchester City,Argentina
2,Neymar Jr,26,92,LW,290000.0,118500000.0,Paris Saint-Germain,Brazil
13,David Silva,32,90,LCM,285000.0,60000000.0,Manchester City,Spain
27,Casemiro,26,88,CDM,285000.0,59500000.0,Real Madrid,Brazil
35,Marcelo,30,88,LB,285000.0,43000000.0,Real Madrid,Brazil
33,P. Aubameyang,29,88,LM,265000.0,59000000.0,Arsenal,Gabon
3,De Gea,27,91,GK,260000.0,72000000.0,Manchester United,Spain
53,I. Rakitić,30,87,RCM,260000.0,46500000.0,FC Barcelona,Croatia
26,M. Salah,26,88,RM,255000.0,69500000.0,Liverpool,Egypt
49,Jordi Alba,29,87,LB,250000.0,38000000.0,FC Barcelona,Spain
38,G. Higuaín,30,88,LS,245000.0,57000000.0,Milan,Argentina
18,M. ter Stegen,26,89,GK,240000.0,58000000.0,FC Barcelona,Germany
19,T. Courtois,26,89,GK,240000.0,53500000.0,Real Madrid,Belgium
105,K. Benzema,30,85,ST,240000.0,37000000.0,Real Madrid,France
54,Piqué,31,87,RCB,240000.0,34000000.0,FC Barcelona,Spain
91,Paulinho,29,85,LDM,235000.0,37000000.0,Guangzhou Evergrande Taobao FC,Brazil
47,R. Lukaku,25,87,ST,230000.0,62500000.0,Manchester United,Belgium

In [131]:
db1.sort_values("Overall", ascending=False).head(30)

,Name,Age,Overall,Position,Wage,Value,Club,Nationality
0,L. Messi,31,94,RF,565000.0,110500000.0,FC Barcelona,Argentina
1,Cristiano Ronaldo,33,94,ST,405000.0,77000000.0,Juventus,Portugal
2,Neymar Jr,26,92,LW,290000.0,118500000.0,Paris Saint-Germain,Brazil
3,De Gea,27,91,GK,260000.0,72000000.0,Manchester United,Spain
4,K. De Bruyne,27,91,RCM,355000.0,102000000.0,Manchester City,Belgium
5,E. Hazard,27,91,LF,340000.0,93000000.0,Chelsea,Belgium
6,L. Modrić,32,91,RCM,420000.0,67000000.0,Real Madrid,Croatia
7,L. Suárez,31,91,RS,455000.0,80000000.0,FC Barcelona,Uruguay
8,Sergio Ramos,32,91,RCB,380000.0,51000000.0,Real Madrid,Spain
12,D. Godín,32,90,CB,125000.0,44000000.0,Atlético Madrid,Uruguay
13,David Silva,32,90,LCM,285000.0,60000000.0,Manchester City,Spain
9,J. Oblak,25,90,GK,94000.0,68000000.0,Atlético Madrid,Slovenia
11,T. Kroos,28,90,LCM,355000.0,76500000.0,Real Madrid,Germany
10,R. Lewandowski,29,90,ST,205000.0,77000000.0,FC Bayern München,Poland
20,Sergio Busquets,29,89,CDM,315000.0,51500000.0,FC Barcelona,Spain
24,G. Chiellini,33,89,LCB,215000.0,27000000.0,Juventus,Italy
23,S. Agüero,30,89,ST,300000.0,64500000.0,Manchester City,Argentina
22,M. Neuer,32,89,GK,130000.0,38000000.0,FC Bayern München,Germany
21,E. Cavani,31,89,LS,200000.0,60000000.0,Paris Saint-Germain,Uruguay
16,H. Kane,24,89,ST,205000.0,83500000.0,Tottenham Hotspur,England
19,T. Courtois,26,89,GK,240000.0,53500000.0,Real Madrid,Belgium
18,M. ter Stegen,26,89,GK,240000.0,58000000.0,FC Barcelona,Germany
17,A. Griezmann,27,89,CAM,145000.0,78000000.0,Atlético Madrid,France
15,P. Dybala,24,89,LF,205000.0,89000000.0,Juventus,Argentina
14,N. Kanté,27,89,LDM,225000.0,63000000.0,Chelsea,France
34,M. Hummels,29,88,LCB,160000.0,46000000.0,FC Bayern München,Germany
41,G. Buffon,40,88,GK,77000.0,4000000.0,Paris Saint-Germain,Italy
40,S. Handanovič,33,88,GK,110000.0,30000000.0,Inter,Slovenia
39,Thiago Silva,33,88,RCB,165000.0,24000000.0,Paris Saint-Germain,Brazil
38,G. Higuaín,30,88,LS,245000.0,57000000.0,Milan,Argentina

In [132]:
db1[db1["Overall"]>=90].groupby("Club")["Name"].count().sort_values(ascending=False)

Club
Real Madrid            3
Atlético Madrid        2
FC Barcelona           2
Manchester City        2
Chelsea                1
FC Bayern München      1
Juventus               1
Manchester United      1
Paris Saint-Germain    1
Name: Name, dtype: int64

In [134]:
db1[db1["Overall"]>=85].groupby("Club")["Name"].count().sort_values(ascending=False)

Club
Real Madrid                       12
Manchester City                   11
Juventus                          11
FC Barcelona                      10
FC Bayern München                  9
Atlético Madrid                    7
Paris Saint-Germain                6
Inter                              6
Tottenham Hotspur                  5
Liverpool                          5
Napoli                             4
Manchester United                  4
Arsenal                            3
Chelsea                            3
Roma                               2
Lazio                              2
LA Galaxy                          1
Milan                              1
Guangzhou Evergrande Taobao FC     1
Olympique Lyonnais                 1
FC Schalke 04                      1
FC Porto                           1
Borussia Dortmund                  1
Beşiktaş JK                        1
Valencia CF                        1
Vissel Kobe                        1
Name: Name, dtype: int64

In [143]:
db1[(db1["Club"]=="FC Barcelona") & (db1["Overall"]>=85)].sort_values("Overall", ascending=False)

,Name,Age,Overall,Position,Wage,Value,Club,Nationality
0,L. Messi,31,94,RF,565000.0,110500000.0,FC Barcelona,Argentina
7,L. Suárez,31,91,RS,455000.0,80000000.0,FC Barcelona,Uruguay
18,M. ter Stegen,26,89,GK,240000.0,58000000.0,FC Barcelona,Germany
20,Sergio Busquets,29,89,CDM,315000.0,51500000.0,FC Barcelona,Spain
32,Coutinho,26,88,LW,340000.0,69500000.0,FC Barcelona,Brazil
42,S. Umtiti,24,87,CB,205000.0,57000000.0,FC Barcelona,France
49,Jordi Alba,29,87,LB,250000.0,38000000.0,FC Barcelona,Spain
53,I. Rakitić,30,87,RCM,260000.0,46500000.0,FC Barcelona,Croatia
54,Piqué,31,87,RCB,240000.0,34000000.0,FC Barcelona,Spain
96,A. Vidal,31,85,CAM,205000.0,26000000.0,FC Barcelona,Chile

In [140]:
db1[db1["Position"]=="GK"].sort_values("Overall", ascending=False).head(30)

,Name,Age,Overall,Position,Wage,Value,Club,Nationality
3,De Gea,27,91,GK,260000.0,72000000.0,Manchester United,Spain
9,J. Oblak,25,90,GK,94000.0,68000000.0,Atlético Madrid,Slovenia
18,M. ter Stegen,26,89,GK,240000.0,58000000.0,FC Barcelona,Germany
19,T. Courtois,26,89,GK,240000.0,53500000.0,Real Madrid,Belgium
22,M. Neuer,32,89,GK,130000.0,38000000.0,FC Bayern München,Germany
37,H. Lloris,31,88,GK,150000.0,36000000.0,Tottenham Hotspur,France
40,S. Handanovič,33,88,GK,110000.0,30000000.0,Inter,Slovenia
41,G. Buffon,40,88,GK,77000.0,4000000.0,Paris Saint-Germain,Italy
46,K. Navas,31,87,GK,195000.0,30500000.0,Real Madrid,Costa Rica
57,Ederson,24,86,GK,125000.0,41500000.0,Manchester City,Brazil
81,Alisson,25,85,GK,115000.0,36500000.0,Liverpool,Brazil
92,W. Szczęsny,28,85,GK,125000.0,32000000.0,Juventus,Poland
133,L. Hrádecký,28,84,GK,74000.0,22000000.0,Bayer 04 Leverkusen,Finland
147,S. Ruffier,31,84,GK,41000.0,19000000.0,AS Saint-Étienne,France
141,Sergio Asenjo,29,84,GK,42000.0,24000000.0,Villarreal CF,Spain
149,K. Schmeichel,31,84,GK,78000.0,19000000.0,Leicester City,Denmark
131,B. Leno,26,84,GK,115000.0,27000000.0,Arsenal,Germany
126,A. Lopes,27,84,GK,72000.0,25000000.0,Olympique Lyonnais,Portugal
128,M. Perin,25,84,GK,105000.0,29500000.0,Juventus,Italy
210,R. Fährmann,29,83,GK,38000.0,20000000.0,FC Schalke 04,Germany
224,Pepe Reina,35,83,GK,56000.0,6000000.0,Milan,Spain
222,R. Jarstein,33,83,GK,33000.0,13000000.0,Hertha BSC,Norway
218,S. Mandanda,33,83,GK,51000.0,13000000.0,Olympique de Marseille,France
214,Y. Sommer,29,83,GK,35000.0,20000000.0,Borussia Mönchengladbach,Switzerland
213,Rui Patrício,30,83,GK,74000.0,16500000.0,Wolverhampton Wanderers,Portugal
212,Adán,31,83,GK,55000.0,15500000.0,Atlético Madrid,Spain
201,D. Subašić,33,83,GK,70000.0,13000000.0,AS Monaco,Croatia
197,O. Baumann,28,83,GK,42000.0,21000000.0,TSG 1899 Hoffenheim,Germany
196,Neto,28,83,GK,41000.0,21000000.0,Valencia CF,Brazil
189,T. Horn,25,83,GK,25000.0,24000000.0,1. FC Köln,Germany